export const _ENV_VARIABLES = {
  JWT_KEY: process.env.JWT_SECRET_KEY,
  STRAPI_CONSTANT: process.env.NEXT_PUBLIC_STRAPI_CONSTANT,
  NEXT_PUBLIC_BACKEND_API_URL: process.env.NEXT_PUBLIC_BACKEND_API_URL,
  NEXT_PUBLIC_BACKEND_API_URL_AWS_LAMBDA:
    process.env.NEXT_PUBLIC_BACKEND_API_URL_AWS_LAMBDA,
};
