export const _ENV_VARIABLES = {
  JWT_KEY: process.env.JWT_SECRET_KEY,
  STRAPI_CONSTANT: process.env.NEXT_PUBLIC_STRAPI_CONSTANT,
  NEXT_PUBLIC_BACKEND_API_URL: process.env.NEXT_PUBLIC_BACKEND_API_URL,
  NEXT_PUBLIC_BACKEND_API_URL_AWS_LAMBDA: process.env.NEXT_PUBLIC_BACKEND_API_URL_AWS_LAMBDA,
  
  RECAPTCHA_KEY: process.env.RECAPTCHA_KEY,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  JWT_SECRET: process.env.JWT_SECRET,
  NEXT_PUBLIC_STRAPI_API_TOKEN: process.env.NEXT_PUBLIC_STRAPI_API_TOKEN,
  NEXT_PUBLIC_PAGE_LIMIT: process.env.NEXT_PUBLIC_PAGE_LIMIT,
  NEXT_PUBLIC_OPENAI_API_KEY: process.env.NEXT_PUBLIC_OPENAI_API_KEY,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  NEXT_PUBLIC_API_USER_NAME: process.env.NEXT_PUBLIC_API_USER_NAME,
  NEXT_PUBLIC_API_PASSWORD: process.env.NEXT_PUBLIC_API_PASSWORD,
  NEXT_PUBLIC_STRAPI_CONSTANT: process.env.NEXT_PUBLIC_STRAPI_CONSTANT,
  
  NEXT_PUBLIC_AWS_S3_BUCKET_SECRET_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_S3_BUCKET_SECRET_ACCESS_KEY,
  NEXT_PUBLIC_AWS_S3_BUCKET_ACCESS_KEY_ID: process.env.NEXT_PUBLIC_AWS_S3_BUCKET_ACCESS_KEY_ID,
  NEXT_PUBLIC_AWS_S3_BUCKET_REGION: process.env.NEXT_PUBLIC_AWS_S3_BUCKET_REGION,
  NEXT_PUBLIC_AWS_S3_ENDPOINT: process.env.NEXT_PUBLIC_AWS_S3_ENDPOINT,

  NEXT_PUBLIC_CURRENT_ENV: process.env.NEXT_PUBLIC_CURRENT_ENV,
  NEXT_PUBLIC_BACKEND_BLACKLIST_CHECK_URL: process.env.NEXT_PUBLIC_BACKEND_BLACKLIST_CHECK_URL,
  NEXT_PUBLIC_DKIM_CHECK_URL: process.env.NEXT_PUBLIC_DKIM_CHECK_URL,
  NEXT_PUBLIC_BACKEND_WEBSOCKET_URL: process.env.NEXT_PUBLIC_BACKEND_WEBSOCKET_URL,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,

  NEXT_PUBLIC_PRICING_TABLE_ID: process.env.NEXT_PUBLIC_PRICING_TABLE_ID,
  NEXT_PUBLIC_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_PUBLISHABLE_KEY,
  NEXT_PUBLIC_SECRET_KEY: process.env.NEXT_PUBLIC_SECRET_KEY,

  NEXT_PUBLIC_STRAPI_API_URL: process.env.NEXT_PUBLIC_STRAPI_API_URL,
  NEXT_PUBLIC_WEBSITE_URL: process.env.NEXT_PUBLIC_WEBSITE_URL,

  NEXT_PUBLIC_CSP_HEADER: process.env.NEXT_PUBLIC_CSP_HEADER,

  NEXT_PUBLIC_AWS_S3_BUCKET_NAME: process.env.NEXT_PUBLIC_AWS_S3_BUCKET_NAME,
};
