import { create } from "zustand";

export const useStore = create((set) => ({
  allDomain: [],
  allVerifiedDomain: [],
  firstDomain: "",
  storedDashboardUrlNew: "",
  subscriptionPlan: "",
  digestReportVal: "",
  dmarcReportVal: "",
  domainReportVal: "",
  alertVal: "",
  isDomainValue: "",
  isMspSuperAdmin: "",
  userRole: "",
  license: {},
  licenseValidation: {},
  historyDate: {},
  userDetail: {},
  setFirstDomain: (url) => set({ firstDomain: url }),
  setAllDomain: (domains) => set({ allDomain: domains }),
  setAllVerifiedDomain: (domainsVerified) => set({ allVerifiedDomain: domainsVerified }),
  setStoredDashboardUrl: (url) => set({ storedDashboardUrlNew: url }),
  setSubscriptionPlan: (planName) => set({ subscriptionPlan: planName }),
  setWeeklyDigestReport: (reportName) => set({ digestReportVal: reportName }),
  setWeeklyDmarcReport: (reportName) => set({ dmarcReportVal: reportName }),
  setWeeklyDomainReport: (reportName) => set({ domainReportVal: reportName }),
  setAlertVal: (alerts) => set({ alertVal: alerts }),
  setIsDomain: (domainCheck) => set({ isDomainValue: domainCheck }),
  setMspSuperAdmin: (isMspVal) => set({ isMspSuperAdmin: isMspVal }),
  setUserole: (roleVal) => set({ userRole: roleVal }),
  setUserDetail: (user) => set({ userDetail: user }),
  setLicense: (data) => set({ license: data }),
  setLicenseValidations: (validateData) =>
  set({ licenseValidation: validateData }),
  setHistoryDate: (data) => set({ historyDate: data }),
}));
